### ISSUE TITLE
bad news:Launchy not python support

### ISSUE THREAD

**Issue by ygao9999** [samsonwang/LaunchyQt#1]
I have been using Launchy for years, me too!
I have writings some python plugins. those  work for me till now.
if you get rid of python support , this is bad news for me.

**Comment by ygao9999** [comment]
![snipaste_2018-11-11_11-05-22](https://user-images.githubusercontent.com/17876875/48308516-cc9aea00-e5a1-11e8-866c-15e3839817ca.png)
not working on window 10.
i am using high dpi desktop,launchy is  ugly interface.

**Comment by ygao9999** [comment]
this guy  rewrite all launchy  plugins  into  one python file using python.
https://github.com/j5shi/Thruster.

**Comment by samsonwang** [comment]
1. Python plugin
I changed plugin interface, so old plugins may not work with launchy 3.0 .
Don't worry, I am trying to fix this.

2. High DPI
It's all about the skin, I guess Launchy main widget in higher DPI would be very tiny?
A main widget scale option would solve this.

**Comment by samsonwang** [comment]
3.0.3 support python
