### ISSUE TITLE
插件问题

### ISSUE THREAD

**Issue by netsonicyxf** [samsonwang/LaunchyQt#10]
1. 原版有Runner和MathyResurrected两个插件，把他们放在plugins目录的Runner和MathyResurrected目录下，重启后程序里没有。
2. 原来的Runner可以用一键启动多个程序，现在的哪个插件可以做到？怎么做？
3. CalcPy，Tasky和Verby没有设置参数界面。

**Comment by samsonwang** [comment]
1. 对于旧版的插件和新版程序不兼容，需要找到它们的源代码，将其移植到新版软件中。
2. Runner插件还没有移植到新版软件中，等移植完成后就能够实现功能了。
3. 这三个插件功能都很简单直接，所以当初设计的时候也就没有安排参数设置界面的功能。（如果有配置需求，可以提出来讨论一下）
-----
对于Runner和MathyResurrected这两个插件，你希望我先移植哪个插件呢？

**Comment by netsonicyxf** [comment]
1. 希望能先移植Runner，MathyResurrected好像和新版的CalcyPy功能差不多。
2. CalcyPy的选项可以参考MathyResurrected的。
