### ISSUE TITLE
3.1.6 add item to catalog doesn't really do anything

### ISSUE THREAD

**Issue by tamarw** [samsonwang/LaunchyQt#108]
**Describe the bug**
Go to Settings > Catalog > +. Nothing appears to happen. But if you hit it enough times, you realize that it is adding items, but there's no way to populate any filenames or directories because there's no option to. Hit Save and then start over; they're gone because they didn't exist anyway.

**To Reproduce**
See above.

**Expected behavior**
Popup for a filepath to enter.

**Screenshots**
Video is probably better, right? https://www.berrycast.com/conversations/41426487-6c41-5a96-9e52-b1bba313f042

**Desktop (please complete the following information):**
 - Operation System: Windows 11 Home 
 - Launchy Version:  3.1.6

**Additional context**
Brand new computer + install and I definitely didn't have this issue before.

**Comment by pro100kryto** [comment]
Try to exit from the application and delete or rename the `config` folder to reset the settings.

**Comment by samsonwang** [comment]
fixed in v3.1.7
