### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by netsonicyxf** [samsonwang/LaunchyQt#11]
**Describe the bug**
程序崩溃.

**To Reproduce**
输入内容，按后退键时发生。

**Expected behavior**
无

**Screenshots**

**Desktop (please complete the following information):**
 - Operation System: Win10 1809
 - Launchy Version: 3.0.7 x64

**Additional context**
dump文件：链接: https://pan.baidu.com/s/12TFyd-pQVpUlm4xM1K6yJg 提取码: 1234

**Comment by samsonwang** [comment]
谢谢你的反馈。
1. 这个bug是每次操作都会复现的么？
2. 这个bug是输入特定的内容后才会复现，还是输入任何内容都会复现？
3. 使用的3.0.7 x64版本是否是带有pip（python的包管理）的呢？

目前，我从这个dump文件中没有找到线索。如果方便的话，请在选项对话框中的系统标签页中将日志级别设置为“调试”，再复现此bug，然后将日志文件发到我邮箱（wangzhilv@gmail.com）吧。
调试模式下的日志文件会包含详细的索引目录信息，如果其中包含敏感信息，再发送之前记得将这些信息删掉。

**Comment by netsonicyxf** [comment]
1. 只记得在短短10及分钟neuron发生过好几次。
2. 不是特定内容，数字，字母都会发现
3. Launchy-3.0.7-win-amd64.zip，不知道带不带pip。
