### ISSUE TITLE
Web Plugin gone after upgrade to 3.1.6

### ISSUE THREAD

**Issue by black-snow** [samsonwang/LaunchyQt#112]
**Describe the bug**
I upgraded to 3.1.6 (vie chocolatey) and suddenly the web plugin is gone:
![grafik](https://github.com/samsonwang/LaunchyQt/assets/579733/1ef4ad12-2c1d-4374-ba17-5246de6ea33c)

This is the most important feature for me.  
I can probably work around it via the runner plugin and calling the web browser directly but it's hitting me hard that all my settings seem to be gone, too.

**To Reproduce**
1. have version < 3.1.6 installed
2. upgrade to 3.1.6

**Expected behavior**
I forgot what it's called but the plugin where you can add shortcuts for web searches is gone - it should still be there (and contain my previous config).

**Screenshots**
![grafik](https://github.com/samsonwang/LaunchyQt/assets/579733/73b75107-39c3-4ccb-97bf-40b8a3aa689b)

**Desktop (please complete the following information):**
 - Operation System: Win11 x64
 - Launchy Version: 3.1.6

**Additional context**
-

**Comment by black-snow** [comment]
Workaround via runner doesn't work with multiple words :/

**Comment by black-snow** [comment]
I think it was called Weby

**Comment by pro100kryto** [comment]
The new name of the plugin is WebSearchPy:
You can found it there: https://github.com/j5shi/Thruster
Read the [readme](https://github.com/samsonwang/LaunchyQt/blob/master/README.org) file to find more plugins.

**Comment by samsonwang** [comment]
fixed in v3.1.7
