### ISSUE TITLE
Allow to copy result from CalcyPy

### ISSUE THREAD

**Issue by netsonicyxf** [samsonwang/LaunchyQt#113]
![image](https://github.com/samsonwang/LaunchyQt/assets/43513391/3bd1e245-8ba3-4978-be45-3f688e732453)
Is it possible to allow user to (auto)copy reslut from CalcyPy in the future version?

**Comment by teknowledgist** [comment]
Doesn't this already work?  I just hit enter and the result is in my clipboard.

**Comment by netsonicyxf** [comment]
I didn't realize that, thank you.

**Comment by netsonicyxf** [comment]
issue resoled
