### ISSUE TITLE
Black border around the icon

### ISSUE THREAD

**Issue by Landius** [samsonwang/LaunchyQt#12]
**Describe the bug**
All my icons in LaunchyQT looks like screeshots below and I don't know why...

**Screenshots**

![2019-4-24_9-4-18](https://user-images.githubusercontent.com/11910028/56626102-e2ddc380-6672-11e9-959e-e991a00b9e2b.png)

![2019-4-24_9-5-14](https://user-images.githubusercontent.com/11910028/56626131-ff79fb80-6672-11e9-882e-730840cfcdc0.png)

![2019-4-24_9-14-5](https://user-images.githubusercontent.com/11910028/56626156-1ae50680-6673-11e9-81d6-739d296bfd13.png)

**Desktop (please complete the following information):**
 - Operation System: Windows 10 1803(17134.706)
 - Launchy Version: 3.0.8

**Additional context**

there's the same problem in the **old launchy**, the icon border is white, though

![2019-4-24_8-50-36](https://user-images.githubusercontent.com/11910028/56626629-13bef800-6675-11e9-87eb-423e43161339.png)

**Comment by samsonwang** [comment]
Thanks for your feedback in the first place.
Earlier, I found this problem in Windows 10 too. 
As it is all good in Win7, and I use Win7 everyday. I guess that older binary(.exe file) icon extracting method is not fully compatible with Win10.
I have put this on the top of my schedule, and will fix this in next release.

**Comment by samsonwang** [comment]
fixed in a5461b1
