### ISSUE TITLE
LaunchyQT's math is wrong

### ISSUE THREAD

**Issue by tamarw** [samsonwang/LaunchyQt#122]
Noticed I couldn't do math today unless I used parentheses which makes no sense. 

Here's an example. 

<img width="230" alt="image" src="https://github.com/samsonwang/LaunchyQt/assets/14209647/d72260e0-96f0-4d9a-8ddf-3884130386f2">

This is the wrong answer. A plus sign does not take priority over a minus sign. The multiplication/division signs do (they have equal weight), but not the +/- and parentheses aren't needed.

This, however, is the right answer, 

<img width="222" alt="image" src="https://github.com/samsonwang/LaunchyQt/assets/14209647/37947b73-4f9d-407c-9d9b-e13193832b53">

I did this with other formulas but wanted to keep this basic - I'm sure it can be fixed now that you have some info to go on. 

Here's the PEMDAS chart that's kind of helpful to go on. There shoudn't have needed to be parentheses here. 

![image](https://github.com/samsonwang/LaunchyQt/assets/14209647/af90382a-9fa7-44b5-9a98-3797b1c72fdf)

**Comment by samsonwang** [comment]
10-2+1+8 = 17
I think this is a right answer.

Subtraction and addition have same precedence, so the calcualtion will be from left to right.

**Comment by tamarw** [comment]
Hang on - that was a bad example, I had a different example and tried to simplify. 

Is there history of whatever is entered into LaunchyQT? Maybe I can find it.

**Comment by samsonwang** [comment]
You may find history in launchy.ini , there is a [History] section. but this section only stores a part of history input.

**Comment by tamarw** [comment]
No history section there but let's see this week when I need to do this again if it's just me being stupid or there's something up.

**Comment by tamarw** [comment]
Closing. I did a bit of backward math there for awhile. Of course Launchy is right. Thanks Samson!
