### ISSUE TITLE
crashes when typing something and delete content by pressing backspace multiple times

### ISSUE THREAD

**Issue by asknet** [samsonwang/LaunchyQt#13]
Hi,

LaunchyQt crashes in the below scenario:

1. Type some chars
2. Delete all chars using backspace
3. Once all chars deleted, press backspace one more time
4. LaunchQt crashes

**Comment by samsonwang** [comment]
Thanks for your feedback.
I followed your steps and can not reproduce this bug on my laptop. So, it is helpful if you could send me your dump file and log file.
Please set logging level to debug in system panel of option dialog, and try to reproduce this problem.
After launchy crashes, send the dump file and log file in system temp folder to me(wangzhilv@gmail.com).

**Comment by secangel** [comment]
Tried using portable mode and it (seemed) solved.

**Comment by GratefulForUpdatedLaunchy** [comment]
I'm very excited to discover this.  Many thanks for reviving Launchy! 

Having same issue.  Tried setting to 'Portable Mode'.  Did not solve.  Did not uninstall previous version of Launchy.  It used my previous settings from %AppData%/Launchy.  That may potentially be the issue?

Log attached, could not upload CrashDumps?  Backed them up from temp directory if they are of use 😊
[launchy.log](https://github.com/samsonwang/LaunchyQt/files/3785791/launchy.log)

**Comment by Heptite** [comment]
I also have this issue. I also am using a previous Launchy config file.

**Comment by GratefulForUpdatedLaunchy** [comment]
Known bug. I have made it a habit to not backspace more than the amount of characters, prevents a crash.

Jan 19, 2020 01:04:19 Just This Guy <notifications@github.com>:
