### ISSUE TITLE
在某些编辑器中，唤出后键入文字，会输入到该编辑器而非launchy中

### ISSUE THREAD

**Issue by eeokee** [samsonwang/LaunchyQt#14]
**Describe the bug**
在微信pc版编辑器里唤出后输入没有聚焦，直接键入字符，会输入微信编辑器

**To Reproduce**
1.打开微信pc版
2.确保输入焦点在微信输入框里
3.通过快捷键唤出launchy
4.键入字符
5.此时不会在launchy输入字符而是会在微信输入框输入
6.其他说明（和输入法无关，中英文均会触发bug，其他软件，如phpstrom等也出现过，但非必现）

**Screenshots**
![1](https://user-images.githubusercontent.com/3079825/57507645-f2773080-7331-11e9-8e3f-6ccc8134ece2.png)

**Desktop (please complete the following information):**
 - Operation System: win10 1803
 - Launchy Version: Launchy-3.0.8-win-amd64-with-pip

**Additional context**
![image](https://user-images.githubusercontent.com/3079825/57507728-2bafa080-7332-11e9-8e6b-f5856fac962c.png)

**Comment by samsonwang** [comment]
感谢反馈，这个问题在我电脑上也复现了。

**Comment by samsonwang** [comment]
已经在 e456a65 改好了，下次发版不会有这个问题了。
