### ISSUE TITLE
CalcyPy plugin cannot include thousand separator

### ISSUE THREAD

**Issue by secangel** [samsonwang/LaunchyQt#18]
For the results of CalcyPy, I would like to include thousand separators in the results, like "1,000" instead of "1000". I tried to update the setting under "Plugins" >> "CalcyPy", select "Show group separator in result" and click "OK", but the setting would not be saved and stayed unchecked.

The original Launchy can support this function and hope this can be catered as well. Thanks!

**Comment by samsonwang** [comment]
![image](https://user-images.githubusercontent.com/11832311/62379959-a592a700-b57a-11e9-95cf-df29a126026d.png)
What is your version? I can not reproduce in v3.0.9

**Comment by secangel** [comment]
Also 3.0.9; I restarted my computer and it works again. Thanks and keep up the great work!
