### ISSUE TITLE
Portable Mode should be simple

### ISSUE THREAD

**Issue by wenmin92** [samsonwang/LaunchyQt#19]
> **Is your feature request related to a problem? Please describe.**

根据安装指引，只需要在安装目录下创建 `config\launchy.ini` 文件即可转为便携模式，实际情况是，这个配置文件必须是完整的，如果创建一个空文件，或只含有少量配置的文件，启动后，会删除该文件，并在 `%appdata\Launchy%` 生成新的配置文件。

> **Describe the solution you'd like**

初次安装时就想使用便携模式，应该允许初始空配置，即空文件或空目录。

> **Describe alternatives you've considered**

或者提供命令行参数进行切换也行。

> **Additional context**

之所以这么要求是因为使用脚本配置。

**Comment by samsonwang** [comment]
我确实没有使用空配置文件测试过，看来这个地方确实要修改下了。
使用命令行参数进行切换也是个不错的选择。

**Comment by wenmin92** [comment]
@samsonwang 文档啊文档，我满心欢喜的想要看看如何使用插件，emmm，都是空白，加油呃

**Comment by samsonwang** [comment]
在 f297a04 修复了，使用了更加合理的portable模式判断策略。
已支持空的 `config` 文件夹和空的 `config/launchy.ini` 文件。
