### ISSUE TITLE
当使用calcypy插件时复制的内容粘贴到其他程序其他程序会奔溃

### ISSUE THREAD

**Issue by eeokee** [samsonwang/LaunchyQt#22]
**Describe the bug**
当使用calcypy插件时复制的内容粘贴到其他程序其他程序会奔溃

**To Reproduce**
1. 按快捷键启动Launchy
2. 输入1+1或者任意计算公式
3. 按回车键（复制计算结果）
4. 粘贴到其他程序（微信PC端，Excel等）
5. 其他程序奔溃，只能通过任务管理器强制结束

**Expected behavior**

**Screenshots**
![GIF](https://user-images.githubusercontent.com/3079825/66547975-ec041380-eb72-11e9-8be5-eacc114e5a3d.gif)

**Desktop (please complete the following information):**
 - Operation System: win10 1903
 - Launchy Version: 3.1.0-win-amd64-with-pip

**Additional context**

**Comment by samsonwang** [comment]
这个问题在 88bb336 修复了，新版程序就不会有这个问题了。
