### ISSUE TITLE
Support Windows Store apps

### ISSUE THREAD

**Issue by marcinsmialek** [samsonwang/LaunchyQt#23]
**Is your feature request related to a problem? Please describe.**
I can't launch Windows Store apps, while they are available in regular Windows Start menu.

**Describe the solution you'd like**
Windows Store apps should be supported just as any link / app

**Describe alternatives you've considered**
One can create shortcuts manually on the desktop with `shell:AppsFolder`, as described here:
https://answers.microsoft.com/en-us/windows/forum/windows_10-windows_store/starting-windows-10-store-app-from-the-command/836354c5-b5af-4d6c-b414-80e40ed14675

**Additional context**
More and more apps are installed with Windows Store, and it would be great to have a convenient way to have them all available in Launchy without messing with such tricks as described in alternatives.
Thanks

**Comment by albertdev** [comment]
I've been using this Launchy fork which has an `uwpapp` plugin: https://github.com/shirosaki/Launchy.

Maybe the author of that fork is willing to share?

**Comment by samsonwang** [comment]
> I've been using this Launchy fork which has an `uwpapp` plugin: https://github.com/shirosaki/Launchy.
> 
> Maybe the author of that fork is willing to share?

Good hint. I could learn from that plugin.

**Comment by netsonicyxf** [comment]
Any progress in "Support Windows Store apps"?

**Comment by samsonwang** [comment]
this feature is added in v3.1.2
