### ISSUE TITLE
删除输入字符程序崩溃

### ISSUE THREAD

**Issue by srliuhao** [samsonwang/LaunchyQt#28]
版本为 Launchy-3.1.0-win-amd64
无论输入中文还是英文，如果删除字符的话，删到最后一个字符程序就会崩溃

运行环境：win10 专业版 64位  10.0.18363 Build 18363

**Comment by samsonwang** [comment]
谢谢你的反馈，这个bug与 #13 是同一个bug，已经修复了，下个版本就不会有这个问题了。

**Comment by srliuhao** [comment]
非常感谢！
