### ISSUE TITLE
启动失败

### ISSUE THREAD

**Issue by Summer1Solstice** [samsonwang/LaunchyQt#29]
运行环境:win10 家庭中文版 操作系统版本号:1909 操作系统版本:18363.535
软件版本:Launchy-3.1.0-win-amd64
问题:无法启动软件,双击运行后弹出窗口(附加图片)
![捕获](https://user-images.githubusercontent.com/46267607/72332765-9604b600-36f5-11ea-967c-708842be1443.PNG)
我找不到崩溃日志在哪里?

**Comment by Summer1Solstice** [comment]
问题解决  启动路径中不能用中文[笑哭]

**Comment by samsonwang** [comment]
谢谢反馈，我还是去查查为啥不能用中文路径吧。

**Comment by Summer1Solstice** [comment]
不客气,加油哦.我很喜欢这款软件,感谢您更新..[比心]
