### ISSUE TITLE
Calcpy Does Not Calculate Minus Figures With Decimals

### ISSUE THREAD

**Issue by secangel** [samsonwang/LaunchyQt#31]
**Describe the bug**
When calculating results with decimals and minus results, the results will not include decimals.
- For example 25-67.8 gives -42 instead of -42.8.
- If the result is positive, no issue is found. 67.8-25 gives 42.8.

**To Reproduce**
1. Open LaunchyQT
2. Enter a calculation with decimals and minus results
3. The result ignores decimals

**Expected behavior**
Negative results should include decimals

**Desktop (please complete the following information):**
 - Operation System: Windows 10 1709
 - Launchy Version: 3.1.1

**Comment by secangel** [comment]
另外如果可以，有小数点的计算可以自动精度吗；现在我设置了 10 位，像 67.8-25 这样会给出 42.8000000000 这样的答案，如果能直接是 42.8 就最好了
不知道在同一个主题下面这样回复是否可以，因为都是 Calcpy 相关~有劳了

**Comment by samsonwang** [comment]
谢谢反馈，这两个bug在都已经记下来了

**Comment by samsonwang** [comment]
已经在 1d9a7a4 修复了这两个问题。
因为CalcyPy是插件，你可以下载并替换这个修改好的 `CalcyPy.py` 文件，这样就不用等到下个软件版本发布了。
