### ISSUE TITLE
为什么没有开机启动功能？

### ISSUE THREAD

**Issue by overXsky** [samsonwang/LaunchyQt#32]
以前的版本还有的，更新后就没了

**Comment by samsonwang** [comment]
之前的开机启动应该是在安装包里提供的功能，新版目前都是以便携版软件提供的，所以就没有自动帮用户加入开机启动项了。目前来看还没有增加“自动加入开机启动项”这个功能的计划。

用户可以手动将软件加入开机启动项中，这个可用的方法有很多，我目前的方式是将软件的快捷方式放入开始菜单的“启动”文件夹中。

**Comment by overXsky** [comment]
谢谢！
