### ISSUE TITLE
Shortcuts to open location of selected file and to run as admin

### ISSUE THREAD

**Issue by CombeeMike** [samsonwang/LaunchyQt#36]
**Is your feature request related to a problem? Please describe.**
I oftentimes find myself in 2 situations which can't be handled with Launchy ATM:
1) I don't want to open/run the file I just found via the normal Launchy search but want to open the explorer in the files location (its parent folder).
2) I'd like to run the file/program/... I just found as an admin

**Describe the solution you'd like**
2 new keyboard shortcuts to perform the mentioned actions:
1) Search for file -> `Ctrl+Shift+Enter` -> Open parent folder of resulting file in default file manager (Win explorer, Nautilus, ...)
2) Search for file -> `Ctrl+Enter` -> Run result as admin

The mentioned shortcuts are just exemplary, feel free to choose whatever you like ;)
E.g. `Ctrl+E` to open folder etc.

**Describe alternatives you've considered**
Create dedicated plugins to perform those actions:
1) Enter something like `folder`, `of` (open folder), `explorer`, ... -> Tab -> Search for file (all indexed files/folders should be available) -> Enter -> Open file manager
2) Enter something like `admin`, `ad`, ... -> Tab -> Search for file (all indexed files/folders should be available) -> Enter -> Open as admin

I'd personally prefer the first solution since the second one requires me (the user) to think of my "real intention" before I start typing whilst the first one allows me to search for the thing I'm looking for and decide what to do after I found it by using the correct shortcut.

**Comment by DustinLuck** [comment]
It looks like this is already possible. Here is what I did:

1. Search for the file as normal
2. Once you have a match, press the Tab key (there will be a triangle pointing to the right)
3. Press the down arrow and choose one of the options

![image](https://user-images.githubusercontent.com/115443/89836687-297f5780-db1c-11ea-8e0e-4e7ecdeb76ab.png)

**Comment by CombeeMike** [comment]
Wow, that is perfect! I just wonder how I could have missed this feature in all the years I've been using Launchy now 😳
