### ISSUE TITLE
Import settings from Launchy

### ISSUE THREAD

**Issue by DustinLuck** [samsonwang/LaunchyQt#38]
As a longtime user of the original Launchy, it would be helpful to import my previous settings. The most important one to me is history. I've spent a long time training Launchy to recognize most programs I use with 2 or three characters. Retraining LaunchyQT would take a good deal of time.

I tried to manually edit the history.db file in the config folder (I'm using LaunchyQT in portable mode), but it is not human readable in any text editor I've used.

**Comment by samsonwang** [comment]
Try edit `launchy.ini` file, paste old entries in "[History]".

**Comment by DustinLuck** [comment]
I have tried copy/pasting the History section from the old ini file to the new one as well as copying the old history.db file. Neither of those had any effect. I have tried both of these options individually and together.

The ini file keeps the items I paste in, but the db file is overwritten when I start Launchy.

Once a new item is added to the ini file by Launchy, I can successfully modify it by changing the search string portion of the entry. However, changing the executable portion causes the search string to stop working altogether.

**Comment by samsonwang** [comment]
`history.db` contains command line history.
Search pattern is stored in launchy.ini "[History]" section, and I guess this is what you want.


Here is a fragment from my launchy.ini

```
[History]
em=runemacs, D:/Program Files/Emacs/bin/runemacs.exe
```

1. Strict to string format  in "[History]", do not omit the space or comma.
2. "D:/Program Files/Emacs/bin/runemacs.exe" must exist in harddrive and must be indexed in Catalog, check Catalog config panel and make sure "runemacs.exe" is scaned into catalog.

**Comment by DustinLuck** [comment]
In my example, I would like to add 7-Zip to my history so that when I type `7z`, it launches. If I add the following to the History section of the ini file and restart Launchy, typing `7z` brings up many matches, but not 7-Zip.

```
[History]
7z=7-zipportable, C:/PortableApps/7-ZipPortable/7-ZipPortable.exe
```

Was the entry for emacs in your history from using Launchy or were you able to successfully add it manually?

**Comment by samsonwang** [comment]
Try this:
```
[History]
7z=7-ZipPortable, C:/PortableApps/7-ZipPortable/7-ZipPortable.exe
```
change "7-zipportable" to "7-ZipPortable" .

**Comment by DustinLuck** [comment]
Thanks, that worked. It seems that the previous version was not case sensitive, whereas the current version is.
