### ISSUE TITLE
QT Project can not be compiled

### ISSUE THREAD

**Issue by acadeus** [samsonwang/LaunchyQt#4]
**Describe the bug**

**To Reproduce**
1. Installed QT 5.11.1
2. Opened Qt Creator Launchy.pro
3. Build All failes

**Screenshots**
![image](https://user-images.githubusercontent.com/47122324/52115738-a66c6f80-260f-11e9-94dd-b23689244efc.png)

**Comment by samsonwang** [comment]
I use VS2015 as develop environment.
Try open "Launchy.sln" in project root directory.

Check out this page, hope it could help you out :)
https://github.com/samsonwang/LaunchyQt/blob/master/docs/HOW_TO_BUILD.org
---
I think it is better to fix the qt project (launchy.pro) and I have put it in my work plan.
