### ISSUE TITLE
launchy crashed after reinstalling with LaunchySetup2.6B2.exe from sourceforge downloads.

### ISSUE THREAD

**Issue by Franvgls** [samsonwang/LaunchyQt#52]
**Launchy stopped working after installing a new skin**. 
It just didn't work pressing alt+space, after that I tryed reinstalling with LaunchySetup2.6B2.exe, but it crashed and asked to send the crash dumps created via sourceforge forums, Haven't been able to find the forum there and have arrived here....
Find the crash dumps here.
Great really great program, it's really difficult working when it does not work.

Best and thanks in advance.
Fran

**To Reproduce**
4. type '...'
5. See error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Operation System: [e.g. windows 7 sp1]
 - Launchy Version: [e.g. 3.0.2]

**Additional context**

**Comment by samsonwang** [comment]
LaunchyQt (in github) is forked from Launchy (in sourceforge), and technically they are two different programs.

According to your problem, try delete Launchy configure files (you can find them in `%AppData%\Roaming\Launchy` ) and the new skin, then restart launchy.

Launchy sourceforge forum: https://sourceforge.net/p/launchy/discussion/

Hope this is helpful.

**Comment by Franvgls** [comment]
Hi samsonwang, 
Thanks a lot for the quick answer, unfortunately it didn't work for me. Have deleted coinfigure files from roaming folder but got the same message after installing/opening launchy,. 
Forgpot to add in my first message Operation system: Windows 10 last update & Launchy tried with 2.5 & 2.6B2

**Comment by Franvgls** [comment]
Finally I got it working againg after uninstalling completely Launchy and reinstalling it.
Thanks a lot.
Best,
