### ISSUE TITLE
Nested folder navigation opens LaunchyQT installation directory instead of selected folder

### ISSUE THREAD

**Issue by gneven** [samsonwang/LaunchyQt#53]
**Describe the bug**
When browsing through nested folders (by repetitively typing the first few letters of a folder and pressing tab) and pressing Enter, an explorer opens in the installation directory of LaunchyQT, rather than in the selected folder.

**To Reproduce**
1. Take any nested folder structure in catalog or create one, e.g., create a folder "aaa" with an empty subfolder "bbb".
2. Press alt-space, aaa, Tab, bbb, Enter

**Expected behavior**
Explorer window opens in folder bbb.

**Desktop (please complete the following information):**
 - Operation System: Windows 10
 - Launchy Version: 3.1.1

**Comment by samsonwang** [comment]
fixed in version 3.1.2
