### ISSUE TITLE
Check for Update not working

### ISSUE THREAD

**Issue by DustinLuck** [samsonwang/LaunchyQt#54]
**Describe the bug**
When I saw a new version was available via github notifications, I used the check update feature in v3.1.1 to see if it would apply the update automatically. Instead, it said there was no update.

**To Reproduce**
1. Right-click the Launchy tray icon ~OR~ go to the Updates tab in the options dialog
2. Click on 'Check for updates'
3. Message says 'No update is available'

**Expected behavior**
Since a new version has been released, I expected that the update would either be applied, automatically downloaded, or a link provided to manually download it.

**Desktop (please complete the following information):**
 - Operation System: Windows 10 v1909 (64-bit)
 - Launchy Version: 3.1.1

**Comment by samsonwang** [comment]
Sorry for this, because the update feed url was https://launchyqt.com/version.xml in v3.1.1, and I did not renew the domain.
The new update feed is https://launchy.wangzhl.com/version.xml, and I have bought this domain for 5 years.
