### ISSUE TITLE
Download links for the 64bit version

### ISSUE THREAD

**Issue by naderi** [samsonwang/LaunchyQt#56]
Hi @samsonwang 
Why are the download links for the 64bit version no longer there?

**Comment by samsonwang** [comment]
Because 32bit program can run on both 32bit and 64bit windows system, but 64bit program can only run on 64bit windows system.
So, I think it is enough to release only 32bit version.

**Comment by naderi** [comment]
Yeah sure, but still it was nice to have the 64bit version too.

**Comment by samsonwang** [comment]
> Yeah sure, but still it was nice to have the 64bit version too.

Could you give a example that shows 64bit version is better than 32bit on 64 bit Windows system.

Forgive my laziness, when I release both 32bit and 64bit version, I need to compile, test, pack, upload for twice.

**Comment by Carlos-DM** [comment]
> > Yeah sure, but still it was nice to have the 64bit version too.
> 
> Could you give a example that shows 64bit version is better than 32bit on 64 bit Windows system.
> 
> Forgive my laziness, when I release both 32bit and 64bit version, I need to compile, test, pack, upload for twice.

Hello! I'm also looking for the 64-bit version. Let me explain why I think it'd be interesing to have it: Currently, the 32-bit LaunchyQt executes 32-bit programs: for example, if I type "cmd" it launches the 32-bit version of the command prompt, and I would like it to launch the 64-bit version (I'm talking of a 64-bit Windows, of course). Windows treats some special folders differently for 32 and 64 bit versions of the same program, and sometimes it is better to launch the 64-bit version.

Consider, for example, you want to edit the file c:\Windows\System32\drivers\etc\hosts --> you write "notepad" in LaunchyQt and the notepad opens. But it is the 32-bit version, so you have to browse to C:\Windows\sysnative\drivers\etc and even I have to write it by hand (not shown in the 32-bit version of the Open file dialog of Windows). On the other hand, if I press Win+R and execute there "notepad", the 64-bit version of notepad opens, and I can quickly open the desired file.

So, please, consider building the 64-bit version again. Thanks!
