### ISSUE TITLE
Build issues with 3.1.2 release under linux

### ISSUE THREAD

**Issue by rezso** [samsonwang/LaunchyQt#57]
- cmake build completely unusable: it requires WinExtras, but the required X11Extras not. In addition, cmake tries to build windows specific plugins: Runner, Tasky, UWPApp, Verby. SKINS_PATH, PLUGINS_PATH, PLATFORMS_PATH undefined. The src/Launchy/Linux/IconProviderLinux.cpp file requires QDir: incomplete type ‘QDir’ used in nested name specifier
- qmake build: liblaunchy.so and libpluginpy.so not exists: these libs are renamed to libLaunchy.so and libPluginPy.so. The version of python hardcoded in the .pro file. And finally ld fails: LaunchyWidget.cpp:(.text+0xa02d): undefined reference to `launchy::runProgram(QString const&, QString const&, bool)'

**Comment by samsonwang** [comment]
Because I do not use linux in my daily life, the 3.1.2 version is only compiled on windows.
I will install a linux system and try to fix this bug.

**Comment by rakslice** [comment]
I found precisely the same things as @rezso for the qmake buidl; I created a pull request #64 with the fixes.

**Comment by DrMerlin** [comment]
Are there some qmake instructions anywhere?  I would like to check this out.

**Comment by rakslice** [comment]
I can't remember the exact steps I followed; it was obvious from how the original qt4 launchy qmake steps worked; it would be approximately:
```
cd src
path/to/your/qt5/bin/qmake -r src.pro
make
sudo make install
```

**Comment by rakslice** [comment]
In I should add that, in alpine linux edge, the packages I needed were: `qt5-qtbase-dev`, `qt5-qtx11extras-dev`, and `python3-dev`, and `qmake` is at `/usr/lib/qt5/bin/qmake`
