### ISSUE TITLE
Nested folder Issue

### ISSUE THREAD

**Issue by gitChaoslord** [samsonwang/LaunchyQt#58]
**Description**
Nested folders don't work correctly for me.   
1) I type a few letters of a folder's name and tab to autocomplete it.
2) No subfolders/files are displayed and typing additonal letters and pressing tab resets the path back to the primary folder.  

(Also, sometimes it get's stuck on a previous selection as you can see in the first seconds of the video, i type in 'Dev' but it autocompletes to 'Tools', a folder i had just used previously)

**LaunchyQT**
https://streamable.com/b99wx3

**Expected**
After having a primary folder selected it should display subfolders/files and by typing additional letters, narrow down the select options to what fits the pattern.

**Launchy vanilla**
https://streamable.com/bqflru

 - Operation System: windows 10 21H1
 - Launchy Version: 3.1.2

**Comment by samsonwang** [comment]
fixed in b3c51265693f6f19d19870924d8e981ca9306097
