### ISSUE TITLE
[Question] Is change of folder structure in release zip permanent?

### ISSUE THREAD

**Issue by albertdev** [samsonwang/LaunchyQt#60]
**Describe the bug**
Release 3.1.1 had a folder structure like this:

```
LaunchyQT-3.1.1-win-x86.7z 
    Launchy-3.1.1-win-x86\
	    Launchy.exe
```

The newest release, 3.1.2 has a folder structure like this:

```
LaunchyQT-3.1.2-win-x86.7z
    Launchy\
	    Launchy.exe
```

I was trying to install LaunchyQT using [chocolatey](https://chocolatey.org/), and this change in structure broke the installer script.

**Expected behavior**
I do not expect a change; I can see how it's simpler when preparing a release (hence why I put `[Question]` in the title).

However, while the chocolatey install script can be fixed,  it would be best if there can be a confirmation that future releases will have their archives built in the same way. If I go bother the maintainer of that install script then I'm sure he would like to know that the next release won't have a different folder name again, thus requiring yet another change to the installer script.

**Comment by samsonwang** [comment]
Sorry, I did not notice that the release zip folder name is important, I was too sloppy before.

I ensure that the zip folder structure for subsequent releases is consistent as V3.1.2.

**Comment by albertdev** [comment]
> Sorry, I did not notice that the release zip folder name is important,

No problem, it's of course the fault of the chocolatey package builder in that they assumed that the zip file structure would never change.

Anyway, I guess my question is answered then, and I'll see if I can get the chocolatey package changed.

Thank you for your response and your work on this project.
