### ISSUE TITLE
Hide tray icon

### ISSUE THREAD

**Issue by TwitchBronBron** [samsonwang/LaunchyQt#62]
Add the ability to hide the tray icon. The original launchy had a setting for that. I don't want to see it in the traybar but I still want launchy to be running in the background. 
![image](https://user-images.githubusercontent.com/2544493/136577396-069d6e9d-0229-4ac6-8554-45ee2c07315f.png)

**Comment by samsonwang** [comment]
fixed in 7b9b1f23e43cb20a3b30ac8712360d6a07e8ed0e
