### ISSUE TITLE
ctrl+alt+shift HotKey

### ISSUE THREAD

**Issue by jlanzarotta** [samsonwang/LaunchyQt#66]
**Is your feature request related to a problem? Please describe.**
I have other applications that take over "ctrl+alt", "ctrl+shift", "ctrl+win".

**Describe the solution you'd like**
Would it be possible to add "ctrl+alt+shift" as another option in the hotkey drop-down?

**Describe alternatives you've considered**
I know of no alternative.

**Additional context**
None.

**Comment by jlanzarotta** [comment]
I would attempt to make this change to the code myself; however, I am not able build it.  Hopefully this project is not dead?

**Comment by samsonwang** [comment]
This project is still alive, but I do not have much time on it this year.

**Comment by jlanzarotta** [comment]
No problem, that is totally understandable.  I am trying to get the code to build.  Once I do, I will try and make a patch.

**Comment by jlanzarotta** [comment]
Okay, "fixed" that error.  Now I am getting:

`Unknown module(s) in QT: winextras`.

Time to figure that one out.

**Comment by jlanzarotta** [comment]
With a bit of reading, I have found that winextras has been deprecated... https://github.com/qt/qtwinextras.  They are saying that winextras has been removed from QT6, which is what I am using, and the code needs to be ported to from QT5 to QT6.  That might be a bit over my head at this time, so I will try and drop back to QT5.

**Comment by jlanzarotta** [comment]
Okay, I dropped back to 5.12.12, am I was able to build successfully.  I will attempt to make a code change.

**Comment by jlanzarotta** [comment]
Okay, I believe I have the code modified and built; however, I do not see not to create the installer?  Any hints on that?

**Comment by samsonwang** [comment]
I did not create installer for LaunchyQt. I used to pack all the ".exe" and ".dll" into a zip file when I want to put up a new version release.

> I specifically need all the QT distribution files... 

If you are coding on a Windows computer, try "windeployqt", this will help you copy all the required Qt files.

**Comment by jlanzarotta** [comment]
Thanks for the information.  I have the code changed; however, I am having difficulties debugging.  I have changed _OptionDialog.cpp_:

`
#ifdef Q_OS_MAC
    m_metaKeys << QString("") << QString("Alt") << QString("Command") << QString("Shift") << QString("Control")
        << QString("Command+Alt") << QString("Command+Shift") << QString("Command+Control");
#else
    m_metaKeys << QString("") << QString("Alt") << QString("Control") << QString("Shift") << QString("Win")
        << QString("Ctrl+Alt") << QString("Ctrl+Shift") << QString("Ctrl+Win");
`

to

`
#ifdef Q_OS_MAC
    m_metaKeys << QString("") << QString("Alt") << QString("Command") << QString("Shift") << QString("Control")
        << QString("Command+Alt") << QString("Command+Shift") << QString("Command+Control");
#else
    m_metaKeys << QString("") << QString("Alt") << QString("Control") << QString("Shift") << QString("Win")
        << QString("Ctrl+Alt") << QString("Ctrl+Shift") << QString("Ctrl+Win") << QString("Ctrl+Alt+Shift");
`

however, it does not seem to work...  The string "Ctrl+Alt+Shift" shows up in the dropdown; however, it is never set correctly.

**Comment by samsonwang** [comment]
Try append `(Qt::ControlModifier | Qt::AltModifier | Qt::ShiftModifier)` to  `m_iMetaKeys` , because `m_iMetaKeys` and `m_metaKeys` are meant to use together.

Addtionally, you should append `QString("Command+Alt+Shift")` to `m_metaKeys` when `Q_OS_MAC` macro exists, this will maitain consistency in MacOS.

**Comment by jlanzarotta** [comment]
Fantastic!  That worked.  Now all I need is to package everything up for deployment.

**Comment by jlanzarotta** [comment]
Okay, I have the QT runtime packages up for distribution...  However, python is a different story.  Any clues on how to package python runtime for distribution?

**Comment by jlanzarotta** [comment]
There are files named "api-ms-win-*".  What are these files and where can I get them for distribution?

**Comment by samsonwang** [comment]
I used to copy python runtime library manually. On Windows, there is a python embeddable package.
https://docs.python.org/3/using/windows.html#windows-embeddable

"api-ms-win-*" files are vcredist files, you can either install the package or copy them from `C:\Windows\System32` or `C:\Windows\SysWOW64` .
https://docs.microsoft.com/en-us/cpp/windows/redistributing-visual-cpp-files

**Comment by jlanzarotta** [comment]
Thanks for the information.  I will take a look into this.
