### ISSUE TITLE
搜首字母可以搜到结果,而搜中文名反而搜索不到

### ISSUE THREAD

**Issue by xjl456852** [samsonwang/LaunchyQt#7]
使用版本:
Launchy-3.0.6-win-amd64.zip
问题:
添加了一个目录作为检索目录,文件类型为*.*
文件中有中文名称.
用首字母能搜到结果.用中文名搜,反而没有结果.
原版launchy无此问题.
麻烦处理下,谢谢

**Comment by samsonwang** [comment]
谢谢你给的反馈，问题现已修复（ 05ea88e ）。
