### ISSUE TITLE
Exclude Launchy appears when some defined applications have focus

### ISSUE THREAD

**Issue by s-kocher** [samsonwang/LaunchyQt#72]
**Is your feature request related to a problem? Please describe.**
When I work remotely with a Citrix remote session, on which I have another Launchy installed, the Launchy shortcut (Alt + Space) is captured by my main computer Launchy instance.

**Describe the solution you'd like**
It will be nice if : 
- In Launchy settings, we can define a list of binaries (example to exclude Citrix : C:\Program Files (x86)\Citrix\ICA Client\wfica32.exe)
- Launchy do not intercept Alt + Space when the application currently having the focus is in this binaries exclusion list
- So Launchy does not display when using Alt+ Space
- And the application having the focus receives correctly the Alt+ Space input (example, if I have Launchy installed on my remote citrix session, it will show up correctly when pressing Alt+ Space)

Bonus : eventually, a list of popular applications can be pre-populated in Launchy default settings (Remote Desktop apps like Microsoft RDP / Teamviewer, Citrix, Virtualization apps like VMware / Virtual Box, ...)

**Describe alternatives you've considered**
Actually, I exit Launchy when I work remotely with my Citrix session

**Additional context**
To be exact, my exact flow is  Main computer with Launchy -> Citrix -> RDP with Launchy ; Alt + Space is intercept by Main computer instead of RDP inside Citrix

**Comment by DustinLuck** [comment]
I can see where this would be a useful feature for some. However, I would not like to see any applications default to this behavior. I do not have Launchy installed on any remote machines that I connect to and always want it to respond to my shortcut no matter what the current app is.

**Comment by samsonwang** [comment]
I will consider this feature as full screan detect, similar to issue #61

**Comment by s-kocher** [comment]
Thanks for considering this feature request. Do not trigger Launchy when in full screen will be a nice solution yes.
Will the application in full screen receive the keyboard input or will launchy catch it, not display but not forwarding the input to the full screen app ?

**Comment by samsonwang** [comment]
> Will the application in full screen receive the keyboard input or will launchy catch it, not display but not forwarding the input to the full screen app ?

@s-kocher 
The keyboard shortcut is catched by operation system and send to launchy.
I will implement it in this way: when some app is running in full screen mode, launchy will ignore keyboard shortcuts.
