### ISSUE TITLE
can be software be even lightweight?

### ISSUE THREAD

**Issue by AHK0** [samsonwang/LaunchyQt#75]
really a piece of nice software. it would be even good if the size is smaller, just like the Launchy itself.
thank you very very much for developing this project

**Comment by AHK0** [comment]
most other similar function softwares are pretty lightweight, including the old Launchy and others such as everything, listary, etc...

**Comment by samsonwang** [comment]
You can delete unwanted plugins, this will make launchy smaller.
The new Launchy is bigger because I add python into it.
Most of the libraries shipped with package are Qt dependencies, they can not remove easily.
