### ISSUE TITLE
设置快捷键为Caps Lock，当触发时会同时触发大小写锁定

### ISSUE THREAD

**Issue by eeokee** [samsonwang/LaunchyQt#8]
**Describe the bug**
原版（2.5）当使用单一快捷键Caps Lock会屏蔽该键默认功能。即按Caps Lock呼出launchy，并不会触发Caps Lock本身大小写锁定（原版若需触发默认Caps Lock可通过Alt+Caps Lock切换大小写锁定），新版3.0.7按 Caps Lock 键，会弹出Launchy同时触发大小写锁定。

**To Reproduce**
1. 按 Caps Lock 键
2. 此时呼出 Launchy，但同时触发了大小写锁定

**Expected behavior**
按 Caps Lock 键，仅呼出 Launchy，不触发大小写锁定，大小写锁定通过 Alt + Caps Lock 切换

**Screenshots**
快捷键配置如下图
![image](https://user-images.githubusercontent.com/3079825/55205149-a8683e80-520c-11e9-970b-57767dd983f8.png)

**Desktop (please complete the following information):**
 - Operation System: windows 10 1809
 - Launchy Version: 3.0.7

**Comment by samsonwang** [comment]
谢谢反馈。快捷键功能在新版重做了，这个CapsLock的问题当时确实没有考虑到。我近期会进行修改的。

**Comment by samsonwang** [comment]
已经在 b56a8af 和 527a9a1 改好了，下次发版的程序就没有这个问题了。

**Comment by eeokee** [comment]
好的，那我先把issue关了
