### ISSUE TITLE
Display custom File icons properly for .url and .lnk

### ISSUE THREAD

**Issue by tdalon** [samsonwang/LaunchyQt#86]
It would be nice when scanning for .url and .lnk files to display the found items with their file icons (not the default one of the linked file type.)
Example of lnk file pointing to .vsb with personalized icon: 
![image](https://user-images.githubusercontent.com/6458444/211743089-c7da0101-ac27-49c6-bc51-2c3597c01fda.png)

![image](https://user-images.githubusercontent.com/6458444/211743166-aa937402-3b35-4e32-aaa4-2c071ef4a57b.png)

Example of .url file with custom icon:

![image](https://user-images.githubusercontent.com/6458444/211743464-1df96bd4-72f4-46b0-bfad-481bbf7119d9.png)

The custom Teams icon is not displayed.

**Comment by DustinLuck** [comment]
I would like to see this too. I have some progressive web apps that don't show the proper icons. The target for one of these shortcuts is `"C:\Program Files (x86)\Google\Chrome\Application\chrome_proxy.exe"  --profile-directory="Profile 19" --app-id=kjgfgldnnfoeklkmfkjfagphfepbbdan`. Launchy doesn't show any icon for this shortcut. The proper icon has been set in the shortcut's properties dialog and appears in File Explorer.

**Comment by samsonwang** [comment]
bug fixed, show *.lnk icon instead of *.lnk target file icon.
