### ISSUE TITLE
用户数据路径自定义

### ISSUE THREAD

**Issue by netsonicyxf** [samsonwang/LaunchyQt#9]
现在版本的用户数据路径在 C:\Users\XXXXX\AppData\Roaming\Launchy 下。
能否自定义这个路径，比如我喜欢把用户数据放在程序路径的data目录下
这样做能实现两个好处：
1. 便携化
2. 放在C盘，如果C盘重装系统，用户数据就没了。

**Comment by samsonwang** [comment]
目前已经支持便携模式了，程序默认运行在安装模式，在选项界面的系统标签页中有配置项可以转换为便携模式。
便携模式会将数据文件存放在程序路径的config目录下。
希望这样能满足你的使用需求。
