### ISSUE TITLE
Disabling plugins does't stick to config.

### ISSUE THREAD

**Issue by RonnyTNL** [samsonwang/LaunchyQt#97]
**Describe the bug**
Disabling plugins does't stick to config. (disable, click OK, open Options and it's back on).

**To Reproduce**
1. ALT-SPACE -> Options.
2. Click on Plugins TAB
3. Disable Calcpy -> click OK
4. Open options again and plugin is enabled again
5. (Running portable mode)

**Expected behavior**
Disabled plugins should stay disabled.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - Operation System: [Win10x64 22H2]
 - Launchy Version: [3.1.5 - Portable]

**Additional context**
N/A

**Comment by samsonwang** [comment]
fixed
